title: Bruna V C Moreira

logo: /assets/cv.jpeg #./assets/cv.png # Use a relative path to logo image 

description: Profissional com experiência em gerência de Operações e Projetos, com atuação em liderança de equipes, gestão de projetos, metodologias ágeis e melhoria de processos. Possui conhecimento e atuação em todo o ciclo de Previdência e Seguros, da originação e emissão, cobrança, endossos, passando por atendimento e pós-venda, regulação e sinistros, até renovações, portabilidade.

github:
  is_project_page: false
  is_user_page: false
